---

- name: Ensure firefox is installed
  become: yes
  yum:
    name: firefox
    state: present

- name: Create new Firefox profile
  environment:
    DISPLAY: :0
  command: firefox -no-remote -CreateProfile {{ profile_name }}

- name: Find profile directory
  find:
    paths: '{{ config_dir }}'
    patterns: '*.{{ profile_name }}'
    file_type: directory
  register: profile_dir

- name: Parse result for profile path
  set_fact:
    profile_path: "{{ profile_dir.files[0].path }}"

- name: Call Firefox Addons API for theme info
  uri:
    url: https://addons.mozilla.org/api/v5/addons/addon/{{ theme_name }}
    return_content: yes
  register: api_call

- name: Parse result for download link
  set_fact:
    theme_download_link: "{{ api_call.json.current_version.file.url }}"

- name: Parse result for guid
  set_fact:
    theme_guid: "{{ api_call.json.guid }}"

- name: Ensure extensions directory exists
  file:
    path: '{{ profile_path }}/extensions'
    state: directory
    mode: 0755

- name: Download theme extension file
  get_url:
    url: "{{ theme_download_link }}"
    dest: '{{ profile_path }}/extensions/{{ theme_guid }}.xpi'
    mode: 0644

# http://kb.mozillazine.org/Profiles.ini_file
- name: Set general options in profiles.ini
  ini_file:
    path: '{{ config_dir }}/profiles.ini'
    section: General
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    mode: 0644
    create: yes
    no_extra_spaces: yes
  loop:
    - { option: StartWithLastProfile, value: 1 }
    - { option: Version, value: 2 }
  loop_control:
    label: "{{ item.option }}"

- name: Define custom profile and set as default
  ini_file:
    path: '{{ config_dir }}/profiles.ini'
    section: Profile0
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    no_extra_spaces: yes
  loop:
    - { option: Name, value: '{{ profile_name }}' }
    - { option: IsRelative, value: 1 }
    - { option: Path, value: '{{ profile_path | basename }}' }
    - { option: Default, value: 1 }
    - { option: Locked, value: 1 }
  loop_control:
    label: "{{ item.option }}"
