---
# Non-catppuccin stuff goes here
- name: Configure base machine
  hosts: all

  tasks:

    - name: Run yum update
      become: yes
      yum:
        name: "*"
        state: latest

    - name: Ensure extra (cool) packages are installed
      become: yes
      yum:
        name:
          - bat
        state: present

    # We need this on for other GUI-based installs to work later.
    - name: Enable auto-login
      become: yes
      ini_file:
        path: /etc/gdm/custom.conf
        section: daemon
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: 0644
        backup: yes
      loop:
      - { option: AutomaticLoginEnable, value: "True"}
      - { option: AutomaticLogin, value: "{{ ansible_user_id }}" }
