---

- name: Test
  hosts: all

  tasks:

    - name: Install neovim
      become: yes
      yum:
        name:
          - neovim
          - python3-neovim
        state: present

    - name: Ensure directory for vim-plug exists
      file:
        path: '{{ ansible_env.HOME }}/.local/share/nvim/site/autoload'
        state: directory
        mode: 0755

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: '{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim'
        mode: 0755
