---
- name: Ensure flatpak is installed
  yum:
    name: flatpak
    state: present

- name: Add the flathub flatpak repository remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

# This seemed to intermittently failed from corrupt downloads.
- name: Install spotify
  flatpak:
    name: com.spotify.Client
    state: present
  retries: 3
  delay: 3
  register: result
  until: result.rc == 0
