---
# Visual Studio Code version number (defaults to the latest version)
vs_code_version: ''
# Mirror server for fetching the public keys and the Visual Studio Code
# installation package. The URL may include directories. The URL must not end
# with a trailing slash.
vs_code_mirror: 'https://packages.microsoft.com'

# Name of package to install. 'code' is the simple default
# Replace with path to local RPM name if not using mirror
vs_code_package: code

# should the gpgcheck of the repo enabled?
# if yes, for dnf/yum the option gpgcheck is set to yes
vs_code_gpgcheck: yes

# skip task to add repo for remote package manager
# if set to yes, the task 'install VS Code repo' will be skipped
# if set to no, the repo will be added, this is the default
vs_code_skip_add_repo: no

# Extensions to install
# Either an identifier of the form ${publisher}.${name}, which will fetch from the internet
# Or a local path to a .vsix file.
vs_code_extensions: ['catppuccin.catppuccin-vsc', '1dot75cm.rpmspec', 'hashicorp.terraform', 'streetsidesoftware.code-spell-checker']

# Settings to use
vs_code_settings: {
            "workbench.colorTheme": "Catppuccin"
}