name: ci

on:
  pull_request:
    types:
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel previous runs
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build
